# These are supported funding model platforms

patreon: HellionRescueProject
custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=Y34DMZYD3DDWN&source=url', 'https://www.buymeacoffee.com/zorkind']
