on:
  release:
    types:
      - "published"

name: Discord Notification

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: binotaliu/action-discord-notifier@v1
        with:
          message-title: New Release
          webhook: https://discordapp.com/api/webhooks/735606198899965962/lQIp9Ho_XEcpt67WA2qnfnOoLmbuEKjXIfJIPyvGS5FnZKN1lfvLrdWxw5IG2abWvsWo
